- TurnPageRoot/TurnPageRoot/settings.py
If you think this is sufficient then we can try merging it! @rohan-sardana let me know if you think this will disrupt things on the AWS side. I included some code to connect it to RDS. However, if we're nervous about merging it before tonight's demo we can try tomorrow.
> local postgres server

- README.md
adding Travis build and coveralls badges in readme for development environment
> updating badges in readme

- TurnPageRoot/TurnPageRoot/settings.py
THIS IS THE ONE! As long as you follow Rohan's instructions in slack to allow your traffic into AWS, you will now connect local builds to our dev db on RDS.
> 129 connect local builds to dev rds db

- .gitignore
- TurnPageRoot/TurnPageRoot/settings.py
- requirements.txt
Fixed version. Env variables for local now rely on django-environ (added this to requirements.txt as well). Still no changes to RDS creds. Env file to be posted in slack
> 129 fix engine setting

- .idea/workspace.xml
- .travis.yml
- TurnPageRoot/TurnPageRoot/settings.py
Trying to create a temp postgres database for travis to use rather than connecting to AWS
> Travis postgres setup

- TurnPageRoot/bookSwiping/views.py
- TurnPageRoot/templates/base.html
> two random books from database

- TurnPageRoot/bookSwiping/tests.py
This test just makes sure the site can still open and display the homepage. It also runs the context actions and makes sure those are pulling from the database correctly. Basically, trying to increase coverage
> Tests for new homepage view function

- TurnPageRoot/static/css/styles.css
- TurnPageRoot/templates/base.html
- requirements.txt
> Color themes implementation02

- TurnPageRoot/static/js/script.js
- on drag down it fades and hides
- fixed bug where if, e.g. you swiped down a lot and then back up and to the right a lot and then back left a bit it wouldn't snap back.
> Set max width for desktop view

- .idea/dataSources.xml
- TurnPageRoot/bookSwiping/templates/bookSwiping/home.html
- TurnPageRoot/bookSwiping/tests/test_book_stack.py
- TurnPageRoot/bookSwiping/tests/text_book_stack.py
- TurnPageRoot/bookSwiping/views.py
- TurnPageRoot/profiles/tests.py
- TurnPageRoot/static/js/script.js
Here's the branch with the ability to swipe through a stack! To run it locally, you need to have at least 15 books inside your database. 
You can use the file below to update your local environment:
[bookSwiping_book2.csv](https://github.com/gcivil-nyu-org/team-3-inperson/files/9853662/bookSwiping_book2.csv)
> 159 make homepage autopopulate with more book covers and users can swipe through books

- .flake8
- TurnPageRoot/TurnPageRoot/settings.py
- TurnPageRoot/bookSwiping/management/commands/bookload.py
- TurnPageRoot/bookSwiping/tests/test_book_stack.py
- TurnPageRoot/bookSwiping/tests/test_views.py
- TurnPageRoot/profiles/admin.py
- TurnPageRoot/profiles/models.py
- TurnPageRoot/utils/db_functions.py
fix: removed E501, F401 as exceptions from flake8 and made the necessary code changes
> fix: flake8 cleanup

- TurnPageRoot/TurnPageRoot/settings.py
- TurnPageRoot/profiles/templates/profiles/login.html
- TurnPageRoot/profiles/templates/profiles/signup.html
> reg page fixed with captcha

- .elasticbeanstalk/config.yml
- .travis.yml
- TurnPageRoot/TurnPageRoot/settings.py
update travis to make it universal for develop and main branch
> 195 fix: travis config

- TurnPageRoot/bookSwiping/urls.py
- TurnPageRoot/bookSwiping/views.py
- TurnPageRoot/static/js/script.js
No testing yet... this might require selenium
> dislike works in database + javascript fixes

- TurnPageRoot/TurnPageRoot/settings.py
- TurnPageRoot/profiles/ids_encoder/__init__.py
- TurnPageRoot/profiles/ids_encoder/converters.py
- TurnPageRoot/profiles/ids_encoder/utils.py
- TurnPageRoot/profiles/templates/profiles/emails/account_activation_email.html
- TurnPageRoot/profiles/templates/profiles/profile.html
- TurnPageRoot/profiles/templates/profiles/user_profile.html
- TurnPageRoot/profiles/tests.py
- TurnPageRoot/profiles/urls.py
- TurnPageRoot/profiles/views.py
- requirements.txt
I will post the new env file on slack group
> User can update and delete their profiles and email verification enhancement

- TurnPageRoot/bookSwiping/tests/test_bookshelf_functionality.py
- TurnPageRoot/bookSwiping/views.py
liked books appear on the top, saved books on the bottom
> bookshelves work properly now (with tests)

- TurnPageRoot/bookSwiping/templates/bookSwiping/home.html
- TurnPageRoot/bookSwiping/views.py
- TurnPageRoot/static/css/styles.css
- TurnPageRoot/static/js/script.js
- TurnPageRoot/templates/base.html
well, it's not perfect but it's responsive! this might be as far as i can get before the code freeze so i can make it look more sharp next sprint.
> modal has arrived

- .travis.yml
- TurnPageRoot/bookSwiping/admin.py
- TurnPageRoot/bookSwiping/modelChoices.py
- TurnPageRoot/bookSwiping/models.py
- TurnPageRoot/bookSwiping/tests/test_book_stack.py
- TurnPageRoot/bookSwiping/views.py
- TurnPageRoot/static/js/script.js
- TurnPageRoot/utils/nyt_load.py
Tests breaking locally, opening a PR bc I ran out of personal Travis credits so I need to consume gcivil credits this way
> Pseudo Rec Engine implemented

- TurnPageRoot/bookSwiping/views.py
Preventing dupes, easy update.
> Remove books on user's bookshelf from pseudo-rec engine results

- TurnPageRoot/static/js/script.js
I think this'll do it but worth pulling down to your device and refreshing / redirecting to the home page a bunch of times to see if it still happens.
> modal plus btn bug
